### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 43

### ISSUE THREAD

**Issue by vincenthawke** [7sDream/torrent_parser#8]
I parsed many torrent files successfully and among >1000 only 1 caused the following error. Hope the stack trace is enough.
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 290, in _next_string
    string = raw.decode(encoding, self._error_handler)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 43: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\pytp.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 632, in __main
    data = TorrentFileParser(
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 202, in parse
    data = self._next_element()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 254, in _next_dict
    for key, element in self._dict_items_generator():
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 247, in _dict_items_generator
    v = self._next_element(k)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 254, in _next_dict
    for key, element in self._dict_items_generator():
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 247, in _dict_items_generator
    v = self._next_element(k)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 266, in _next_list
    return [element for element in self._list_items_generator()]
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 266, in <listcomp>
    return [element for element in self._list_items_generator()]
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 260, in _list_items_generator
    element = self._next_element()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 254, in _next_dict
    for key, element in self._dict_items_generator():
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 247, in _dict_items_generator
    v = self._next_element(k)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 266, in _next_list
    return [element for element in self._list_items_generator()]
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 266, in <listcomp>
    return [element for element in self._list_items_generator()]
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 260, in _list_items_generator
    element = self._next_element()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 350, in _next_element
    element = self._type_to_func(element_type)()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\torrent_parser.py", line 304, in _next_string
    raise InvalidTorrentDataException(
torrent_parser.InvalidTorrentDataException: Fail to decode string at pos 22408 using encoding utf-8
```

**Comment by 7sDream** [comment]
See: https://github.com/7sDream/torrent_parser/issues/4#issuecomment-399634500

**Comment by 7sDream** [comment]
Close due to not active.
